name: BlueskyPlugin
version: 1.0
main: com.example.blueskyplugin.BlueskyPlugin
api-version: 1.13
commands:
  bsky:
    description: Blueskyのコマンド
    usage: /bsky <login|logout|post|tl>
    permission: bluesky.use 